### ISSUE TITLE
Adding a web-based image utility

### ISSUE THREAD

**Issue by MR-DHRUV** [Rakeshgombi/Hactoberfest-2022#26]
hey @Rakeshgombi, I want to add a web-based image utility that can do the following changes
✅ Grayscale
✅ Blur
✅ Saturate
✅ Contrast
✅ Hue
✅ Invert
✅ Brightness

**Comment by Rakeshgombi** [comment]
Hi, Thank you for the Interest please read the contribution guidelines and make a PR. Contributions are always welcome.🙂

Happy Hacktoberfest💐
